<MyCalc>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        GridLayout:
            cols:2
            size_hint_y: 0.20

            GridLayout:
                cols: 1
                rows: 3
                spacing: -2
                size_hint_x: 0.20

                Button:
                    id: dec_btn
                    text: "DEC"
                    on_press: root.conversions("2dec")
                Button:
                    id: hex_btn
                    text: "HEX"
                    on_press: root.conversions("2hex")
                Button:
                    id: bin_btn
                    text: "BIN"
                    on_press: root.conversions("2bin")

            GridLayout:
                cols: 1
                size_hint_x: 0.80

                ScrollView:
                    id: scroll
                    size_hint: (1.0, 0.10)
                    do_scroll_x: True
                    do_scroll_y: False
                    bar_inactive_color: (23/255,23/255,23/255,1)

                    Label:
                        id: calc_label
                        text: ""
                        size_hint_x: None
                        width: 2000
                        font_size: 20
                        background_color: (23/255,23/255,23/255,1)
                        color: (247/255, 242/255, 242/255)
                        canvas.before:
                            Color:
                                rgba: self.background_color
                            Rectangle:
                                size: self.size
                                pos: self.pos
                        multiline: False
                        text_size: self.size
                        valign: "center"
                        padding_x : 5

                TextInput:
                    id: calc_input
                    text: "0"
                    halign: "right"
                    readonly: True
                    size_hint: (1.0, 0.15)
                    font_size: 35
                    background_color: (23/255, 23/255, 23/255)
                    foreground_color: (247, 242, 242)
                    multiline: False
                    padding_y: (self.height - self.line_height) / 2

        GridLayout:
            cols: 5
            rows: 7
            spacing: 0.5
            size_hint_y: .80

            # row 1

            Button:
                id: alt_btn
                text: "2nd"
                font_size: 22
                size_hint: (1,1)
                color: (247/255, 242/255, 242/255)
                background_normal: ''
                background_color: (43/255, 43/255, 43/255)
                on_press: root.special("alt")
            Button:
                id: sin_btn
                text: "sin"
                font_size: 22
                size_hint: (1,1)
                color: (247/255, 242/255, 242/255)
                background_normal: ''
                background_color: (55/255, 55/255, 55/255)
                on_press: root.trigonometric("sin")
            Button:
                id: cos_btn
                text: "cos"
                font_size: 22
                size_hint: (1,1)
                color: (247/255, 242/255, 242/255)
                background_normal: ''
                background_color: (55/255, 55/255, 55/255)
                on_press: root.trigonometric("cos")
            Button:
                id: tan_btn
                text: "tan"
                font_size: 22
                size_hint: (1,1)
                color: (247/255, 242/255, 242/255)
                background_normal: ''
                background_color: (55/255, 55/255, 55/255)
                on_press: root.trigonometric("tan")
            Button:
                id: deg_btn
                text: "Deg(°)"
                font_size: 22
                size_hint: (1,1)
                color: (247/255, 242/255, 242/255)
                background_normal: ''
                background_color: (43/255, 43/255, 43/255)
                on_press: root.trigonometric("deg")

            # row 2

            Button:
                id: pow_btn
                text: "x²"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (55/255, 55/255, 55/255)
                on_press: root.special("pow")
            Button:
                text: "C"
                font_size: 22
                size_hint: (1,1)
                color: (247/255, 242/255, 242/255)
                background_normal: ''
                background_color: (43/255, 43/255, 43/255)
                on_press: root.all_clear()
            Button:
                text: "del"
                font_size: 22
                size_hint: (1,1)
                color: (247/255, 242/255, 242/255)
                background_normal: ''
                background_color: (43/255, 43/255, 43/255)
                on_press: root.special("del")
            Button:
                text: "mod"
                font_size: 20
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.operations('%')
            Button:
                text: "÷"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.operations('÷')

            # row 3

            Button:
                id: sqr_btn
                text: "√x"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (55/255, 55/255, 55/255)
                on_press: root.special("sqr")
            Button:
                id: seven_btn
                text: "7"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('7')
            Button:
                id: eight_btn
                text: "8"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('8')
            Button:
                id: nine_btn
                text: "9"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('9')
            Button:
                text: "×"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.operations('×')

            # row 4

            Button:
                id: log_btn
                text: "log"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (55/255, 55/255, 55/255)
                on_press: root.special("log")
            Button:
                id: four_btn
                text: "4"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('4')
            Button:
                id: five_btn
                text: "5"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('5')
            Button:
                id: six_btn
                text: "6"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('6')
            Button:
                text: "-"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.operations('-')

            # row 5

            Button:
                id: percent_btn
                text: "%"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (55/255, 55/255, 55/255)
                on_press: root.special("%")
            Button:
                id: one_btn
                text: "1"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('1')
            Button:
                id: two_btn
                text: "2"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('2')
            Button:
                id: three_btn
                text: "3"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('3')
            Button:
                text: "+"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.operations('+')

            # row 6

            Button:
                id: one_over_x
                text: "1/x"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (55/255, 55/255, 55/255)
                on_release: root.special('1/x')
            Button:
                text: "0"
                font_size: 28
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                on_press: root.clicked('0')
            Button:
                text: "."
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.multidec()
            Button:
                text: "("
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.brackets('(')
            Button:
                text: ")"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (65/255, 65/255, 65/255)
                on_press: root.brackets(')')

            # row 7

            Button:
                id: pi_btn
                text: "π"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (55/255, 55/255, 55/255)
                on_press: root.special('pi')
            Button:
                text: "MS"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (94/255, 145/255, 142/255)
                on_press: root.saved_value('ms')
            Button:
                text: "MR"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (94/255, 145/255, 142/255)
                on_press: root.saved_value('mr')
            Button:
                text: "+/-"
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (247/255, 242/255, 242/255)
                background_color: (55/255, 55/255, 55/255)
                on_press: root.pos_neg()
            Button:
                text: "="
                font_size: 22
                size_hint: (1,1)
                background_normal: ''
                color: (0,0,0)
                background_color: (17/255,123/255,189/255)
                on_press: root.result()

